name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # o la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para GitHub Pages
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"  # ¡Clave! Aumenta memoria a 6 GB para CSV grandes
          BASE_PATH: '/'  # ¡Cambio clave! Raíz para repos <username>.github.io
          # Descomenta y agrega secrets si usas fuentes de datos
          EVIDENCE_SOURCE__mother__token: ${{ secrets.EVIDENCE_SOURCE__MOTHER__TOKEN }}
          # EVIDENCE_SOURCE__my_source__username: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__USERNAME }}
          # EVIDENCE_SOURCE__my_source__private_key: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__PRIVATE_KEY }}
        run: |
          npm run sources
          npm run build  # Asegúrate de que salga a ./build (sin subcarpeta)

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'  # ¡Cambio clave! Sin subcarpeta del repo

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

