name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # or whichever branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Permite a Git LFS descargar los archivos grandes rastreados
          lfs: true
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          # Establece la ruta base para SvelteKit/Evidence.
          # Debe ser el nombre del repositorio, no el evento completo.
          # Por ejemplo, si el repo es 'spainfacts.github.io', el BASE_PATH es '/spainfacts.github.io'
          #BASE_PATH: '/${{ github.event.repository.name }}' 
          BASE_PATH: '/spainfacts.github.io' # Podrías usar esto si lo anterior falla
          
          ## Añade y descomenta cualquier variable de entorno aquí
          ## EVIDENCE_SOURCE__my_source__username: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__USERNAME }}
          ## EVIDENCE_SOURCE__my_source__private_key: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__PRIVATE_KEY }}
        run: |
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # SvelteKit/Evidence generalmente construye en 'build' o 'out'. 
          # Usaremos 'build' y la ruta completa del repositorio para compatibilidad con BASE_PATH.
          path: 'build' 

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
